info:
  title: Example API
  version: 1.0.0
openapi: 3.0.0
paths:
  /pet:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  category:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                    type: object
                  id:
                    type: integer
                  name:
                    type: string
                  photoUrls:
                    items:
                      type: string
                    type: array
                  status:
                    enum:
                    - available
                    - pending
                    - sold
                    type: string
                  tags:
                    items:
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                      type: object
                    type: array
                type: object
          description: Successful response
      summary: Get pet details
  /pet/{petId}/uploadImage:
    post:
      parameters:
      - in: path
        name: petId
        required: true
        schema:
          type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  petId:
                    type: integer
                type: object
          description: Successful upload
      summary: Upload an image
servers:
- url: https://example.test
